# These are supported funding model platforms

# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: raheesahmed
custom: https://www.upwork.com/freelancers/raheesahmed
